plugins { id 'com.android.application' }

android {
    namespace 'com.sthefany.myvirtualpc'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sthefany.myvirtualpc'
        minSdk 23
        targetSdk 30
        versionCode 3
        versionName '0.3.0'
        ndk { abiFilters 'armeabi-v7a' }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
}
